#!/usr/bin/env bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Edit chezmoi state
# @raycast.mode silent
#
# Optional parameters:
# @raycast.packageName Chezmoi
# @raycast.icon 📝

set -euo pipefail

# get root of repo
state_dir="$(chezmoi git -- rev-parse --show-toplevel)"
config_path="${HOME}/.config/chezmoi/chezmoi.toml"

code --folder-uri "file://${state_dir}" --file-uri "file://${config_path}"
