#!/usr/bin/env bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Start work apps
# @raycast.mode silent
#
# Optional parameters:
# @raycast.packageName Workflows
# @raycast.icon 🔛

apps=(
    "/Applications/Firefox.app"
    "/Applications/iTerm.app"
    "/Applications/Logseq.app"
    "/Applications/Slack.app"
    "/Applications/Visual Studio Code.app"
    "/Applications/Microsoft Outlook.app"
    "/Applications/Keybase.app"
)

for app in "${apps[@]}"; do
    open -g "$app" &
done
