[gpg]
  recipient = "chezmoi-state@gpg.ldaws.net"

[data]
  code_command = "code"
  editor = "/usr/local/bin/vim"
  ssh_pkcs11_provider = "/usr/local/lib/ssh-keychain.dylib"
  visual_editor = "/usr/local/bin/code -w"
  work_machine = true

[data.git]
  signing_key = "0xA0BE84DBE2E93076"
  envato_email = "..."
  personal_email = "..."

[data.gpg]
  default_key = "0xA0BE84DBE2E93076"
  trusted_key = "0xA0BE84DBE2E93076"

  pinentry = "/usr/local/bin/pinentry-mac"
