version: '3.8'
services:
  jaeger:
    container_name: global-jaeger
    image: quay.io/jaegertracing/all-in-one:1.43
    restart: on-failure
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - user_global
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
networks:
  user_global: {}
