#!/usr/bin/env bash

# fallback for when mise isn't initialized in the shell
if test -d "$HOME/.local/share/mise/shims" && [[ $PATH != *"$HOME/.local/share/mise/shims"* ]]; then
    export PATH="$HOME/.local/share/mise/shims:$PATH"
fi

if test -e "$HOME/.private_profile"; then
    # shellcheck disable=SC1091
    source "$HOME/.private_profile" 
fi
