#!/usr/bin/env bash

set -Eeuo pipefail

setup_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

script_dirs=(
  "$setup_dir"
)

kernel_name="$(uname -s || true)"

if [[ "$kernel_name" == "Darwin" ]]; then
  script_dirs+=(
    "${setup_dir}/macos"
  )
elif [[ "$kernel_name" == "Linux" ]]; then
  script_dirs+=(
    "${setup_dir}/linux"
  )

  distro_id="$(lsb_release --id --short || true)"

  if [[ -n "$distro_id" ]]; then
    script_dirs+=(
      "${setup_dir}/$(echo "$distro_id" | tr '[:upper:]' '[:lower:]')"
    )
  fi
fi

for dir in "${script_dirs[@]}"; do
  if [[ -d "$dir" ]]; then
    echo "Running scripts from $(basename "$dir")"

    for script in $(find "$dir" -maxdepth 1 -type f -perm -500 \( -iname '*.sh' -or -iname '*.fish' \) | sort -n); do
      "$script"
    done
  fi
done
