#!/usr/bin/env bash -l
# shellcheck disable=SC2096

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Open work & office apps (OOA)
# @raycast.mode silent
#
# Optional parameters:
# @raycast.icon 🔛

set -euo pipefail

SHELL="$(dscl . read "/Users/$USER" UserShell | awk '{ print $2; }')"
export SHELL

cd "$(dirname "${BASH_SOURCE[0]}")" && ./work
