#!/usr/bin/env bash

set -euo pipefail

apps=(
    "/Applications/Firefox.app"
    "/Applications/iTerm.app"
    "/Applications/Slack.app"
    "${HOME}/Applications/Chrome Apps.localized/Google Meet.app"
    "$@" # extra apps via CLI args
)

for app in "${apps[@]}"; do
    if [ -r "$app" ]; then
      open -g "$app" &
    fi
done
