#!/usr/bin/env bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Open work & home apps (OHA)
# @raycast.mode silent
#
# Optional parameters:
# @raycast.icon 🔛

extra_apps=(
    "/Applications/Elgato Control Center.app"
    "/Applications/Elgato Stream Deck.app"
)

cd "$(dirname "${BASH_SOURCE[0]}")" && ./work "${extra_apps[@]}"
