#!/usr/bin/env bash

set -euo pipefail

apps=(
    "/Applications/Firefox.app"
    "/Applications/iTerm.app"
    "/Applications/Logseq.app"
    "/Applications/Slack.app"
    "/Applications/Visual Studio Code.app"
    "/Applications/Microsoft Outlook.app"
    "/Applications/Keybase.app"
    "$HOME/Applications/Keybase.app"
    "$@" # extra apps via CLI args
)

for app in "${apps[@]}"; do
    if [ -r "$app" ]; then
      open -g "$app" &
    fi
done
