#!/usr/bin/env bash -l
# shellcheck disable=SC2096

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Open work & home apps (OHA)
# @raycast.mode silent
#
# Optional parameters:
# @raycast.icon 🔛

set -euo pipefail

SHELL="$(dscl . read "/Users/$USER" UserShell | awk '{ print $2; }')"
export SHELL

extra_apps=(
    "/Applications/Elgato Control Center.app"
    "/Applications/Elgato Stream Deck.app"
)

cd "$(dirname "${BASH_SOURCE[0]}")" && ./work "${extra_apps[@]}"

SwitchAudioSource -f cli -t input -s "RODECaster Pro II Secondary"
SwitchAudioSource -f cli -t output -s "RODECaster Pro II Secondary"
