#!/usr/bin/env bash

# TODO: unhardcode JDK/etc. for Linux

export JAVA_HOME="/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/"
export ANDROID_SDK_ROOT="${HOME}/Library/Android/sdk"
build_tools_path="$(find "${ANDROID_SDK_ROOT}/build-tools" -type d -depth 1 | head)"
export PATH="${PATH}:${ANDROID_SDK_ROOT}/platform-tools:${build_tools_path}:${ANDROID_SDK_ROOT}/tools/bin"

"${@:-$SHELL}"
