#!/usr/bin/env bash

set -Eeuo pipefail

if ! command -v mise >/dev/null 2>&1; then
    echo "expected mise to be installed"
    exit 1
fi

if [ -d "/Library/Java/JavaVirtualMachines" ]; then
    for version in $(mise ls --installed --plugin java | awk '{ print $2; }'); do
        dest_path="/Library/Java/JavaVirtualMachines/${version}.jdk"

        if [[ -r "$dest_path" ]]; then
            echo "== Link already exists for ${version}"
            echo
            continue
        fi

        echo "== Linking ${version}"

        (
            set -x
            sudo mkdir -p "$dest_path"
            sudo ln -s "$(mise where "java@${version}")/Contents" "${dest_path}/Contents"
        )

        echo
    done
fi
