#!/usr/bin/env bash

apps=(
  "/Applications/Firefox.app"
  "/Applications/iTerm.app"
  "/Applications/Slack.app"
  "/Applications/WorkFlowy.app"
  "/Applications/Joplin.app"
  "/Applications/DevHub.app"
  "/Applications/Microsoft To Do.app"
  "/Applications/Trello.app"
)

for app in "${apps[@]}"; do
  open -g "$app"
done
