#!/usr/bin/env bash

apps=(
  "/Applications/Elgato Control Center.app"
)

for app in "${apps[@]}"; do
  open -g "$app"
done

SwitchAudioSource -s "Arctis Pro Wireless Game"
SwitchAudioSource -t input -s "C922 Pro Stream Webcam"
