#!/usr/bin/env bash

apps=(
	"/Applications/Elgato Control Center.app"
	"/Applications/Elgato Stream Deck.app"
)

for app in "${apps[@]}"; do
	# seems like there's a race condition between Stream Deck and Control Center sometimes?
	# maybe this will avoid the issue?
	if [[ "$app" = "/Applications/Elgato Stream Deck.app" ]]; then
		sleep 2
	fi

	open -g "$app"
done

SwitchAudioSource -s "Arctis Pro Wireless Game"
SwitchAudioSource -t input -s "Shure MV7"
