#!/usr/bin/env bash

apps=(
	"/Applications/Firefox.app"
	"/Applications/Gather.app"
	"/Applications/iTerm.app"
	"/Applications/Logseq.app"
	"/Applications/Slack.app"
	"/Applications/Trello.app"
	"/Applications/Visual Studio Code.app"
)

for app in "${apps[@]}"; do
	open -g "$app" &
done
